/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Course: typeof import('./src/components/UI/Course.vue')['default']
    EndingPage: typeof import('./src/components/UI/EndingPage.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Profile: typeof import('./src/components/UI/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Something: typeof import('./src/components/UI/Something.vue')['default']
    Splash: typeof import('./src/components/UI/Splash.vue')['default']
    Step: typeof import('./src/components/UI/Step.vue')['default']
  }
}
