/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutUs: typeof import('./src/components/UI/TabContents/AboutUs.vue')['default']
    Chatbot: typeof import('./src/components/UI/Simulation/Chatbot.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    CompanyTab: typeof import('./src/components/UI/Simulation/tabs/CompanyTab.vue')['default']
    Course: typeof import('./src/components/UI/Home/Course.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EmailPopup: typeof import('./src/components/EmailPopup.vue')['default']
    EndingPage: typeof import('./src/components/UI/Home/EndingPage.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    IntroductionCotent: typeof import('./src/components/UI/Simulation/IntroductionCotent.vue')['default']
    MarketTab: typeof import('./src/components/UI/Simulation/tabs/MarketTab.vue')['default']
    Overview: typeof import('./src/components/UI/TabContents/Overview.vue')['default']
    Profile: typeof import('./src/components/UI/Home/Profile.vue')['default']
    Reviews: typeof import('./src/components/UI/TabContents/Reviews.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarMenu: typeof import('./src/components/UI/Simulation/SidebarMenu.vue')['default']
    SituationTab: typeof import('./src/components/UI/Simulation/tabs/SituationTab.vue')['default']
    Something: typeof import('./src/components/UI/Home/Something.vue')['default']
    Splash: typeof import('./src/components/UI/Home/Splash.vue')['default']
    Step: typeof import('./src/components/UI/Home/Step.vue')['default']
    Task1Content: typeof import('./src/components/UI/Simulation/tasks/Task1Content.vue')['default']
    Task2Content: typeof import('./src/components/UI/Simulation/tasks/Task2Content.vue')['default']
    Task3Content: typeof import('./src/components/UI/Simulation/tasks/Task3Content.vue')['default']
    TaskContent: typeof import('./src/components/UI/Simulation/TaskContent.vue')['default']
    TaskMenuItem: typeof import('./src/components/UI/Simulation/TaskMenuItem.vue')['default']
    Tasks: typeof import('./src/components/UI/TabContents/Tasks.vue')['default']
    TeamTab: typeof import('./src/components/UI/Simulation/tabs/TeamTab.vue')['default']
  }
}
